### ISSUE TITLE
Figure 6 -  Fix - client provided kid - 

### ISSUE THREAD

**Issue by ciseng** [ace-wg/pubsub-profile#19]
[Marco Review]
* The public key of Figure 6 (in 'client_cred') and of Figure 9 (in
'pub_keys') includes also the 'kid' header parameter. This is not
mentioned earlier in the text describing the Joining Request and Joining
Response.

    In particular for 'client_cred' in the Joining Request, this gives
the impression that it is up to the client to self-assign a 'kid' value
to its own public key. This can later result in collisions, i.e. two
publishers may have a public key with the same 'kid' value. Later on,
this in turn puts a subscriber at least in a situation where it might
have to try verifying a message signature using different public keys,
until the right one is used.

    I think it's better that the KDC exclusively determines these
identifiers, as uniquely associated not only to the public key for its
retrieval but also to the corresponding publisher client. As to the
actual provisioning of these identifiers, there are two ways:

    a) The one currently used in the Joining Response, where that
identifier is the value of the 'kid' header parameter; or, as I believe
a better option,

    b) The separate 'peer_identifiers' parameter defined in Section
4.1.2.1 of KG.

    In either case, I think it's fine later on in Section 5.1 to have a
published message specifying in the 'kid' COSE parameter the identifier
to use for retrieving the right public key.

[CS: Will need to think about this - but yes, it needs fixing]

**Comment by marco-tiloca-sics** [comment]
This was addressed in version -07 of the draft.
