### ISSUE TITLE
In order to encrypt the message, how do you build the AEAD nonce

### ISSUE THREAD

**Issue by ciseng** [ace-wg/pubsub-profile#22]
* I suppose the empty string for the 'external_aad' applies to both the
encryption and the signing process. Correct?

[CS: That was my understanding]
 

* In order to encrypt the message, how do you build the AEAD nonce?

    All the group members have the same Base IV received in the Joining
Response, and clearly they are not expected to synchronize with one
another about their individual message counter used as Partial IV.
Hence, the basic Message IV construction constisting in xoring the Base
IV with the zero-padded Partial IV yields the risk of reusing the same
(nonce, key) pair.

    If the KDC exclusively assigns the identifiers for public keys and
group members (see comment above), it should work to build the AEAD
nonce in a similar way like OSCORE does, see [5].

    That would also mean having a quite smaller Partial IV in the
unprotected header of the COSE_Encrypt0 object, while now in Figure 12
it consistently has a size of 7 bytes as expected for the AEAD nonce by
AES-CCM-64-64-128.

    [5] https://datatracker.ietf.org/doc/html/rfc8613#section-5.2

[CS: I need to have Francesca's opinion on this, as I have not contributed here.]

**Comment by marco-tiloca-sics** [comment]
This was addressed in version -08 of the draft.
