### ISSUE TITLE
Define a rekeying approach

### ISSUE THREAD

**Issue by ciseng** [ace-wg/pubsub-profile#24]
Is there any plan about defining a rekeying approach in this
document? I think that a basic point-to-point approach can be pretty
much like the one defined in Section 20 of KGO, although filling the
'key' parameter as defined in this document. It might actually be even
simpler as to the provided content, since you may not need to provide
additional information to support a recovery for group members that have
missed a rekeying instance, like KGO has to do.

[CS: I think we should]

**Comment by ciseng** [comment]
==>MT
Please, see also the new Section 6 "Group Rekeying Process" in the Editor's copy of ace-key-groupcomm, which considers also guidelines for a point-to-point rekeying scheme.

This is supposed to be minimally supported by a KDC, which can however opt for a more advanced scheme to be indicated in the Joining Response (see Section 4.3.1 "POST Handler" in the Editor's copy of ace-key-groupcomm).
<==

**Comment by marco-tiloca-sics** [comment]
Addressed and closed by https://github.com/ace-wg/pubsub-profile/commit/11b8902396d98feb140e1a461cd8d773ddda0213
